# Lab 1-2 - Środowisko Programistyczne + Wprowadzenie do uczenia maszynowego

## Konfiguracja środowiska programistycznego
### Google Colab: https://colab.research.google.com/github/yy/dviz-course/blob/master/docs/m01-intro/lab01.ipynb
### Pycharm: https://www.jetbrains.com/help/pycharm/creating-virtual-environment.html

## Przydatne linki

### Integracja Colab-GitHub: https://colab.research.google.com/github/googlecolab/colabtools/blob/master/notebooks/colab-github-demo.ipynb

### Synchronizacja Pycharm-Github: https://www.jetbrains.com/help/pycharm/github.html

### Podstawy operacji na ramkach danych w Pandas: https://www.kaggle.com/learn/pandas

### Tworzenie wykresów w seaborn: https://www.kaggle.com/code/vijayjoshi17/seaborn-guide-all-important-plots

# Zadania:

## Ocena zadań
### Zasady oceniania dla listy 1:
Student w ciągu 5-6 minut prezentuje i omawia napisany przez siebie kod, a następnie prowadzący zadaje 1-2 pytania do całości listy w celu werfikacji czy student rozumie kod, który zaprezentował.

Za każde zadanie można dostać maksymalnie 2 punkty.

### Ocena jest redukowana o 1 punkt w przypadku:
- niepełnej realizacji polecenia (np. brak jednego z podpunktów)
- niezdolności do odpowiedzi na pytanie ze zrozumienia kodu
- popełnienia błędu w kodzie

## Wykorzystywane zbiory danych
Poniższa lista zadań wykorzystuje dwa zbiory danych dostępne na platformie Kaggle:

### Dla zadań 1-4:

Student Lifestyle and Academic Performance Dataset: https://www.kaggle.com/datasets/sehaj1104/student-lifestyle-and-academic-performance-dataset

### Dla zadania nr 5:

Social Media Viral Content and Engagement Metrics: https://www.kaggle.com/datasets/aliiihussain/social-media-viral-content-and-engagement-metrics

## Dokumentacje bibliotek potrzebnych do realizacji zadań:
- pandas: https://pandas.pydata.org/docs/index.html
- seaborn: https://seaborn.pydata.org/
- matplotlib: https://matplotlib.org/stable/

In [1]:
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

## Zadanie 1
Wyświetl ramkę danych spełniającą następujące kryteria:
- ramka zawiera wyłącznie informacje o wieku studentów oraz tym jak spędzają czas.
- ramka zawiera informacje wyłącznie o 15 studentach z najwyższą średnią (CGPA)
- ramka jest posortowana pod względem średniej, tak by student z najwyższą średnią był wyświetlany jako pierwszy

In [16]:
df = pd.read_csv('student_lifestyle_performance_dataset.csv')

df_sorted = df.sort_values(by='CGPA', ascending=False)

top_15 = df_sorted.head(15)

wynik = top_15[['Age', 'Study_Hours_per_Day', 'Gym_Hours_per_Week', 'Screen_Time_Hours', 'Sleep_Hours']]

print(wynik)

     Age  Study_Hours_per_Day  Gym_Hours_per_Week  Screen_Time_Hours  \
657   22                 6.85               12.67               3.84
109   23                 5.83                6.05               7.19
843   24                 4.64                3.59               3.28
405   17                 6.87               18.13               2.21
464   25                 5.18                7.85               7.92
171   20                 8.05                0.00               6.46
475   19                 5.71               12.96               2.98
639   19                 7.30                8.24               3.96
659   20                 3.85                5.21               7.14
682   25                 4.87                0.00               4.95
156   24                 5.41                0.21               5.62
902   25                 7.70                0.00               4.73
904   19                 5.50                9.23               2.12
940   24                 5.54                7.50               4.70
768   24                 8.01                1.80               7.07

     Sleep_Hours
657         8.45
109         9.26
843         8.34
405         7.92
464         9.13
171         7.34
475         8.07
639         8.57
659         9.22
682         8.25
156         7.66
902         6.21
904         6.13
940         9.41
768         6.77

## Zadanie 2
dodaj do ramki danych kolumnę z wyliczoną średnią ilością czasu wolnego, którym student dysponuje w ciągu dnia.


### Wyliczając wartość czasu wolnego przyjmij następujące założenia:
- czas wolny studenta to cały czas, którego **NIE** poświęca na naukę, ćwiczenia, sen oraz siedzenie przed ekranem oraz na jedzenie i czynności higieniczne
- około godzina czasu spędzonego przed ekranem to czas poświęcony na naukę
- jedzenie i czynności higieniczne zajmują przeciętnej osobie 2,5 godziny w ciągu dnia

### Następnie wyświetl otrzymaną ramkę danych tak, by spełniała następujące kryteria:
- wyświetl wyłącznie dodatkową kolumnę oraz kolumny wykorzystane do wyliczenia ilości czasu wolnego
- kolumna z czasem wolnym powinna wyświetlać się jako pierwsza z lewej
- czas wolny powinien być zaokrąglony do drugiej liczby po przecinku

In [13]:
df['Czas_wolny'] = 24 - df['Study_Hours_per_Day'] - df['Screen_Time_Hours'] +
1 - 2.5 - df['Gym_Hours_per_Week']/7 - df['Sleep_Hours']

df['Czas_wolny'] = df['Czas_wolny'].round(2)

columns = [
    'Study_Hours_per_Day',
    'Gym_Hours_per_Week',
    'Sleep_Hours',
    'Screen_Time_Hours'
]

columns_to_print = ['Czas_wolny'] + columns

table = df[columns_to_print]
display(table)

,Czas_wolny,Study_Hours_per_Day,Gym_Hours_per_Week,Sleep_Hours,Screen_Time_Hours
0,1.91,4.14,2.67,6.84,9.23
1,5.69,5.97,15.61,5.52,3.09
2,10.54,3.19,2.52,3.39,5.02
3,2.08,4.77,0.00,6.44,9.21
4,4.36,5.42,9.93,6.54,4.76
...,...,...,...,...,...
995,6.60,4.60,12.64,5.26,4.23
996,7.64,4.02,2.86,6.55,3.88
997,5.15,4.28,0.00,8.43,4.64
998,3.74,6.42,10.08,6.06,4.84
999,4.40,2.35,1.91,8.30,7.18

## Zadanie 3
utwórz ramkę danych pozwalającą odpowiedzieć na następujące pytania
- Jaka dziedzina naukowa (*Branch*) jest najbardziej stresująca?
- Czy mediana snu wśród studentów informatyki (*IT*) jest wyższa niż wśród studentów mechaniki (*Mechanical*)?
### UWAGA!
Uwzględnij wyłącznie informacje o pełnoletnich studentach.

In [21]:
over_eighteen = df[df['Age'] >= 18]
table_3 = over_eighteen.groupby('Branch').agg(avg_stress_level=('Stress_Level_1_to_10', 'mean'),
median_of_sleep_hours=('Sleep_Hours', 'median')).reset_index()

table_3 = table_3.sort_values(by='avg_stress_level', ascending=False)
display(table_3)

       Branch  avg_stress_level  median_of_sleep_hours
1       Civil          4.630494                  6.710
2         ECE          4.626014                  6.405
5  Mechanical          4.608940                  6.640
3  Electrical          4.544621                  6.310
0         CSE          4.526667                  6.540
4          IT          4.454929                  6.755

## Zadanie 4
Przedstaw na wykresach:
- zależność między czasem snu a osiąganą średnią z uwzględnieniem diety studenta
- średnią obecność na zajęciach dla poszczególnych dziedzin naukowych
### UWAGA!
potraktuj informatykę (*IT*) i inżynierię komputerową (*CSE*) jako jedną dziedzinę

## Zadanie 5:
Utwórz wykresy, które pozwalają przedstawić następujące informacje:
- Najpopularniejsze tematy filmów na YouTube Shorts w ostatnim kwartale 2024 roku
- Jaki hasztag najbardziej opłaca się umieszczać w  postach na poszczególnych platformach?